### ISSUE TITLE
GW spectrum normalization in fixedbackground expansion

### ISSUE THREAD

**Issue by Bai-Zhan** [cosmolattice/cosmolattice#8]
The gravitational wave spectrum is usually normalized with $\rho_c = 3H^2/8\pi G$.

In file "gwpowerspectrum.h", we can see that the spectrum is normalized with ```Energies::rho(model)```, 
which calculates the total energy for all the fields we evolve.

This is correct for self-consistent expansion.
However, for a fixedbackground expansion, the scale factor as well as the Hubble parameter do not depend on the the evolvfing fields.

Therefore, I think that the normalization factor should be something like:
```
T rho_tot = 3*pow<2>(model.aDotI/model.aI)/(8*pi*G);
```
This should also save the time on calculating field energies.

**Comment by dgfigueroa** [comment]
Dear Bai-Zhan,

Sorry very much for the late reply, I was meant to answer you before the summer break but I got buried in tasks before my holidays and at the end I missed to answer you. 

So, first of all, thanks for your remark!

For the fixedbackground expansion the code gives you the ratio of energy density of GWs to the source energy density, because that's the relevant physical information at the time of production (i.e. how much GWs you produce out of your field sources). Of course, if you want to redshift that background to the present, you first need to multiply by the ratio of the GW source energy density to the background energy density (3m_p^2H^2), so in that way you will obtain the fraction that you wanted, and then you can multiply by the standard Omega_rad^(0) and change-of-dof pre-factors to redshift the amplitude. 

So it is not whether the normalization factor should be one or another, it's just a matter of understanding what the code is giving you as output. Of course, your observation is still valid and we will consider in future updates to add an extra column in the output file of GWs with the ratio to the background, so people don't get confused.

Best wishes, Dani
